# ======================================================================================== #
#     ___ _ _   _        _        _      _   _             ___           __ _
#    / __(_) |_| |_ _  _| |__    /_\  __| |_(_)___ _ _    / __|___ _ _  / _(_)__ _
#   | (_ | |  _| ' \ || | '_ \  / _ \/ _|  _| / _ \ ' \  | (__/ _ \ ' \|  _| / _` |
#    \___|_|\__|_||_\_,_|_.__/ /_/ \_\__|\__|_\___/_||_|  \___\___/_||_|_| |_\__, |
#                                                                            |___/
# ======================================================================================== #

# Add 'dags' to any changes within 'dags' directory or any subfolders
dagster: "dags/**/*"

# Add 'data' to any changes within 'data' directory or any subfolders
data: "data/**/*"

# Add 'kubernetes' to any changes within 'k8s' directory or any subfolders
kubernetes: "k8s/**/*"

# Add 'iac' to any changes within 'iac' directory or any subfolders
iac: "iac/**/*"

# Add 'workflows' to any changes within 'workflows' directory or any subfolders
workflows: ".github/workflows/**/*"

# Add 'resto' to any changes within 'resto' directory or any subfolders
resto: "resto/**/*"

# Add 'tests' to any changes within 'tests' directory or any subfolders
tests: "tests/**/*"

# Add 'scripts' to any changes within '*.md' files
scripts: "{**/*.sh, *.sh}"

# Add 'documentation' to any changes within '*.md' files
documentation: "{**/*.md, *.md}"
